### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by zalph** [lorensiuswlt/NewAndroidTwitter#5]
Hello,
I am currently testing your nice implementation of twitter. However, I keep getting the following error. 
## and would like to know if you have an idea of what could cause this.

My code is pretty straight forward and I also have the callback url assigned which from surfing the web seems to cause a bottleneck sometimes. 
Could you please advise if you have encountered something along these lines 
Here is my code:
mTwitter is just a wrapper class  that handles the initializations  etc.

```
if (!mTwitter.hasValidSession()) {
        mTwitter.authorize(new SigninListener() {

            @Override
            public void onSuccess(OauthAccessToken accessToken,
                    String userId, String screenName) {
                // showToastMessage("Hello " + screenName);
                handleShareOnTwitterHelper();

            }

            @Override
            public void onError(String error) {
                showToastMessage("ErrorTweet = " + error);

            }
        });
    } else {
        handleShareOnTwitterHelper();
    }

private void handleShareOnTwitterHelper() {
try {

        mTwitter.updateStatus(
                getShout(),
                new net.londatiga.android.twitter.TwitterRequest.RequestListener() {

                    @Override
                    public void onSuccess(String response) {
                        showToastMessage("Your Tweet Has been posted");
                        // mTwitter.logout();
                    }

                    @Override
                    public void onError(String error) {
                        showToastMessage("onSubmitTweet #" + error);

                    }
                });

    } catch (Exception e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
```

}

Here is my logcat;
    10-31 18:58:26.615: W/DefaultRequestDirector(17358): Authentication error: Unable to respond to any  of these challenges: {}
    10-31 18:58:26.615: W/System.err(17358): java.lang.Exception: Authorization Required
    10-31 18:58:26.615: W/System.err(17358):    at    net.londatiga.android.twitter.http.HttpConn.connectPost(HttpConn.java:122)
    10-31 18:58:26.615: W/System.err(17358):    at    net.londatiga.android.twitter.TwitterRequest$RequestTask.doInBackground(TwitterRequest.java:70)

**Comment by praveen2gemini** [comment]
This code not works to me. Is there anything did I miss to configure ? help me to find out ?

EXCEPTION:1
11-14 10:00:53.960: W/System.err(3231): java.net.MalformedURLException: Unknown protocol: oauth
11-14 10:00:53.960: W/System.err(3231):     at java.net.URL.<init>(URL.java:184)
11-14 10:00:53.960: W/System.err(3231):     at java.net.URL.<init>(URL.java:127)
11-14 10:00:53.960: W/System.err(3231):     at net.londatiga.android.twitter.TwitterDialog.processVerifier(TwitterDialog.java:152)
11-14 10:00:53.960: W/System.err(3231):     at net.londatiga.android.twitter.TwitterDialog.access$1(TwitterDialog.java:148)
11-14 10:00:53.960: W/System.err(3231):     at net.londatiga.android.twitter.TwitterDialog$TwitterWebViewClient.shouldOverrideUrlLoading(TwitterDialog.java:179)
11-14 10:00:53.960: W/System.err(3231):     at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:274)
11-14 10:00:53.960: W/System.err(3231):     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:376)
11-14 10:00:53.960: W/System.err(3231):     at android.os.Handler.dispatchMessage(Handler.java:99)
11-14 10:00:53.960: W/System.err(3231):     at android.os.Looper.loop(Looper.java:137)
11-14 10:00:53.960: W/System.err(3231):     at android.app.ActivityThread.main(ActivityThread.java:4745)
11-14 10:00:53.960: W/System.err(3231):     at java.lang.reflect.Method.invokeNative(Native Method)
11-14 10:00:53.960: W/System.err(3231):     at java.lang.reflect.Method.invoke(Method.java:511)
11-14 10:00:53.960: W/System.err(3231):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-14 10:00:53.960: W/System.err(3231):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-14 10:00:53.960: W/System.err(3231):     at dalvik.system.NativeStart.main(Native Method).

EXCEPTION: 2
11-14 10:00:54.016: W/EGL_genymotion(3231): eglSurfaceAttrib not implemented
11-14 10:00:54.020: W/InputMethodManagerService(2390): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@53865188 attribute=android.view.inputmethod.EditorInfo@5384b7a4
11-14 10:00:56.476: W/DefaultRequestDirector(3231): Authentication error: Unable to respond to any of these challenges: {oauth=www-authenticate: OAuth realm="https://api.twitter.com"}
11-14 10:00:56.476: W/System.err(3231): java.lang.Exception: Authorization Required
11-14 10:00:56.476: W/System.err(3231):     at net.londatiga.android.twitter.oauth.OauthProvider.retreiveAccessToken(OauthProvider.java:207)
11-14 10:00:56.476: W/System.err(3231):     at net.londatiga.android.twitter.Twitter$AccesTokenTask.doInBackground(Twitter.java:222)
11-14 10:00:56.476: W/System.err(3231):     at net.londatiga.android.twitter.Twitter$AccesTokenTask.doInBackground(Twitter.java:1)
11-14 10:00:56.476: W/System.err(3231):     at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-14 10:00:56.476: W/System.err(3231):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-14 10:00:56.476: W/System.err(3231):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-14 10:00:56.476: W/System.err(3231):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
11-14 10:00:56.476: W/System.err(3231):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-14 10:00:56.476: W/System.err(3231):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-14 10:00:56.476: W/System.err(3231):     at java.lang.Thread.run(Thread.java:856)
